# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loog < Formula
  desc "Kubernetes resource history viewer (TUI)"
  homepage "https://github.com/loog-project/loog"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/loog-project/loog/releases/download/v1.0.0/loog_1.0.0_macos_amd64.tar.gz"
      sha256 "ccb99fda552441402fdc887e1984dcd2012ae8f56774eb463ae569a554cb5307"

      define_method(:install) do
        bin.install "loog"
        generate_completions_from_executable(bin/"loog", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/loog-project/loog/releases/download/v1.0.0/loog_1.0.0_macos_arm64.tar.gz"
      sha256 "224dda9e414f7844975b5bdd9de06244b99c3cc4fe483cad44dc5fd4e4fe95da"

      define_method(:install) do
        bin.install "loog"
        generate_completions_from_executable(bin/"loog", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/loog-project/loog/releases/download/v1.0.0/loog_1.0.0_linux_amd64.tar.gz"
      sha256 "31dec1b174698dd0313357d191627ec17cb68abc3a324c8ad8b24064c898db8b"
      define_method(:install) do
        bin.install "loog"
        generate_completions_from_executable(bin/"loog", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/loog-project/loog/releases/download/v1.0.0/loog_1.0.0_linux_arm64.tar.gz"
      sha256 "ca09fb9392d4ffb420e67a928bf27bfbf61ff7cd2edaab1e9fc2ac2af551a1dc"
      define_method(:install) do
        bin.install "loog"
        generate_completions_from_executable(bin/"loog", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/loog version")
  end
end
